name: "Deploy To AWS for testing the AWS CI/CD"
on:
  push:
    branches:
      - dev_deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SERVER_IP: ${{ vars.SERVER_IP }}
      DockerUser: ${{vars.Docker_user}}

    steps:
      - uses: actions/checkout@v4

      - name: "Docker Image Builder"
        run: |
          docker login -u $DockerUser -p $DOCKERHUB_PAT
          docker build -t $DockerUser/portfolio:v1
          docker push $DockerUser/portfolio:v1
        env:
          DOCKERHUB_PAT: ${{ secrets.DOCKERHUB_PAT }}
        
      - name: "Setting SSH"
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo -e "Host *\\ntStrictHostKeyChecking no\n\n" > ~/.ssh/config
          touch ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
       
      - name: "SSH key to docker"
        run: |
          touch pem.pem
          echo $SSH_KEY64 | base64 -d > pem.pem && chmod 600 pem.pem
          ssh-keygen -R $SERVER_IP
        env:
          SSH_KEY64: ${{ secrets.SSH_KEY64 }}

      - name: "Docker Restarting and pulling"
        run: \
          ssh -t ubuntu@$SERVER_IP -i pem.pem 'docker pull $DockerUser/portfolio:v1'
          ssh -t ubuntu@$SERVER_IP -i pem.pem  'docker stop portfolio && docker rm portfolio'
          ssh -t ubuntu@$SERVER_IP -i pem.pem  'docker run --name portfolio -p 80:80 -d  $DockerUser/portfolio:v1'

